/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.SecretaryForms;

import DatabasePackage.*;
import java.util.ArrayList;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author afernandez
 */
public class SecretaryApprovePatientAccount extends javax.swing.JFrame {

    /**
     * Creates new form SecretaryApprovePatientAccount
     */
    static String currentUserID;
    public SecretaryApprovePatientAccount(String userID) {
        initComponents();
        this.currentUserID = userID;
        SetCombValues();
    }
    public void SetCombValues(){
        ArrayList<String> a = new ArrayList<String>();
            for (int i = 0; i < SystemDatabase.accountRequests.size(); i++) {

                a.add(SystemDatabase.accountRequests.get(i).getFirstname());
            
        }
        
        for (String value : a) {
                CombPatientName.addItem(value); 
        }
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CombPatientName = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtPatientInfo = new javax.swing.JTextArea();
        BtnShowRequest = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        TxtIDNum = new javax.swing.JTextField();
        BtnCreatePatientAccount = new javax.swing.JButton();
        BtnCancel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        BtnRefuseAccount = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Approve patient Account");

        jLabel2.setText("Select User");

        CombPatientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombPatientNameActionPerformed(evt);
            }
        });

        TxtPatientInfo.setColumns(20);
        TxtPatientInfo.setRows(5);
        jScrollPane1.setViewportView(TxtPatientInfo);

        BtnShowRequest.setText("Show request");
        BtnShowRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnShowRequestActionPerformed(evt);
            }
        });

        jLabel3.setText("Enter Patient's ID: ");

        BtnCreatePatientAccount.setText("create new user");
        BtnCreatePatientAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCreatePatientAccountActionPerformed(evt);
            }
        });

        BtnCancel.setText("Cancel");
        BtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelActionPerformed(evt);
            }
        });

        jLabel4.setText("P");

        BtnRefuseAccount.setText("Refuse account request");
        BtnRefuseAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRefuseAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CombPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnShowRequest))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtIDNum, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnRefuseAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnCreatePatientAccount)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CombPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnShowRequest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtIDNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnCreatePatientAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnRefuseAccount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnCancel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CombPatientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombPatientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CombPatientNameActionPerformed

    private void BtnShowRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnShowRequestActionPerformed
        // TODO add your handling code here:
        String combValue = CombPatientName.getSelectedItem().toString();
        TxtPatientInfo.setText("");
        
        for (int i = 0; i < SystemDatabase.accountRequests.size(); i++) {
            if (SystemDatabase.accountRequests.get(i).getFirstname().equals(combValue)) {
                TxtPatientInfo.setText(SystemDatabase.accountRequests.get(i).getFirstname() + "\n"+ 
                       SystemDatabase.accountRequests.get(i).getSurname() + "\n"+ 
                       SystemDatabase.accountRequests.get(i).getAddress() + "\n"+  
                       SystemDatabase.accountRequests.get(i).getAge()     + "\n"+  
                       SystemDatabase.accountRequests.get(i).getGender());
                break;
            }
        }
    }//GEN-LAST:event_BtnShowRequestActionPerformed

    private void BtnCreatePatientAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCreatePatientAccountActionPerformed
        // TODO add your handling code here:
        String combValue = CombPatientName.getSelectedItem().toString();
        outerloop:
         for (int i = 0; i < SystemDatabase.accountRequests.size(); i++) {
            if (SystemDatabase.accountRequests.get(i).getFirstname().equals(combValue)) 
            {
                String ID = ("P"+ TxtIDNum.getText());
                for (int j = 0; j < SystemDatabase.userArray.size(); j++) {
                    if (ID.equals(SystemDatabase.userArray.get(j).getUserID())) {
                        showMessageDialog(null, "ID already exists, please enter a new one.");
                        break outerloop;
                    }
                }
                
                String firstname = SystemDatabase.accountRequests.get(i).getFirstname();
                String surname = SystemDatabase.accountRequests.get(i).getSurname();
                String address = SystemDatabase.accountRequests.get(i).getAddress();
                String password = SystemDatabase.accountRequests.get(i).getPassword();
                String age = SystemDatabase.accountRequests.get(i).getAge();
                String gender = SystemDatabase.accountRequests.get(i).getGender();
                
                UserFactory.getUserType(ID, firstname, surname, address, password, age, gender);
                SystemDatabase.accountRequests.remove(i);
                showMessageDialog(null, "New user created with ID: " + ID);
                SystemDatabase.SaveAccountRequests();
                SystemDatabase.SaveUserArray();
                new SecretaryHome(currentUserID).setVisible(true);
                this.dispose();               
                break;
                
            }
         }
    }//GEN-LAST:event_BtnCreatePatientAccountActionPerformed

    private void BtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelActionPerformed
        // TODO add your handling code here:
        new SecretaryHome(currentUserID).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnCancelActionPerformed

    private void BtnRefuseAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRefuseAccountActionPerformed
        // TODO add your handling code here:
        String combValue = CombPatientName.getSelectedItem().toString();
        
        for (int i = 0; i < SystemDatabase.accountRequests.size(); i++) {
            if (SystemDatabase.accountRequests.get(i).getFirstname().equals(combValue)) 
            {
                SystemDatabase.accountRequests.remove(i);
                SystemDatabase.SaveAccountRequests();
                showMessageDialog(null, "Account request denied, request deleted");
                new SecretaryHome(currentUserID).setVisible(true);
                this.dispose();               
                break;
            }
            
        }
    }//GEN-LAST:event_BtnRefuseAccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecretaryApprovePatientAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecretaryApprovePatientAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecretaryApprovePatientAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecretaryApprovePatientAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecretaryApprovePatientAccount(currentUserID).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancel;
    private javax.swing.JButton BtnCreatePatientAccount;
    private javax.swing.JButton BtnRefuseAccount;
    private javax.swing.JButton BtnShowRequest;
    private javax.swing.JComboBox<String> CombPatientName;
    private javax.swing.JTextField TxtIDNum;
    private javax.swing.JTextArea TxtPatientInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
