/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.PatientForms;

import DatabasePackage.IUser;
import DatabasePackage.SystemDatabase;
import javax.swing.JOptionPane;

/**
 *
 * @author afernandez
 */
public class PatientHome extends javax.swing.JFrame {

    /**
     * Creates new form PatientHome
     */
    private static PatientHome obj = null;
    
    static String currentID;
    public PatientHome(String userID) {
        initComponents();
        this.currentID = userID;
        LblTitle.setText("Welcome, " + SystemDatabase.FindUser(currentID).getUserFirstname());
    }
    
    //makes sure that only one patient home form is opened
    public static PatientHome getObj()
    {
        if (obj == null) {
            obj = new PatientHome(currentID);
        } return obj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblTitle = new javax.swing.JLabel();
        BtnRequestAppointment = new javax.swing.JButton();
        BtnCreateDoctorFeedback = new javax.swing.JButton();
        BtnRequestDeletion = new javax.swing.JButton();
        BtnviewAppointment = new javax.swing.JButton();
        BtnViewPrescription = new javax.swing.JButton();
        BtnViewhistory = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTitle.setText("Welcome, Patient");

        BtnRequestAppointment.setText("Request appointment");
        BtnRequestAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRequestAppointmentActionPerformed(evt);
            }
        });

        BtnCreateDoctorFeedback.setText("Create doctor feedback");
        BtnCreateDoctorFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCreateDoctorFeedbackActionPerformed(evt);
            }
        });

        BtnRequestDeletion.setText("Request account deletion");
        BtnRequestDeletion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRequestDeletionActionPerformed(evt);
            }
        });

        BtnviewAppointment.setText("View appointment");
        BtnviewAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnviewAppointmentActionPerformed(evt);
            }
        });

        BtnViewPrescription.setText("View current prescription");
        BtnViewPrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewPrescriptionActionPerformed(evt);
            }
        });

        BtnViewhistory.setText("View history");
        BtnViewhistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewhistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnViewhistory, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnRequestDeletion))
                    .addComponent(LblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnRequestAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnCreateDoctorFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnviewAppointment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnViewPrescription, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnviewAppointment, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(BtnRequestAppointment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnCreateDoctorFeedback, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(BtnViewPrescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnViewhistory, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(BtnRequestDeletion)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCreateDoctorFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCreateDoctorFeedbackActionPerformed
        // TODO add your handling code here:
        new PatientDoctorFeedback(currentID).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnCreateDoctorFeedbackActionPerformed

    private void BtnRequestAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRequestAppointmentActionPerformed
        // TODO add your handling code here:
        new PatientRequestAppointment(currentID).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnRequestAppointmentActionPerformed

    private void BtnRequestDeletionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRequestDeletionActionPerformed
        // shows a warning message before sending off the warning message
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog (null, "are you sure you want to request account termination?","Warning",dialogButton);
        boolean IDExists = false;
        if (dialogResult == JOptionPane.YES_OPTION) {
            //if yes is selected, it checks if the user has allready requested their account to be deleted
            //if it has, shows a message saying their request has already gone through before
            for (int i = 0; i < SystemDatabase.patientDeleteRequest.size(); i++) {
                if (SystemDatabase.patientDeleteRequest.get(i).equals(currentID)) {
                System.out.println("You have allreayd requested account deletion, please be patient");
                IDExists = true;
                break;
                }
            }
            if (IDExists != true) {
                //if the ID does not exist, it adds the current ID to the deletion request array
            SystemDatabase.patientDeleteRequest.add(currentID);
            SystemDatabase.saveDeleteRequestArray();
            } else
            {
            System.out.println("Already exists");
            }

        }
    }//GEN-LAST:event_BtnRequestDeletionActionPerformed

    private void BtnviewAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnviewAppointmentActionPerformed
        // opens the view appointment form
        new PatientViewAppointment(currentID).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnviewAppointmentActionPerformed

    private void BtnViewhistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewhistoryActionPerformed
        // opens view history form
        new PatientViewHistory(currentID).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnViewhistoryActionPerformed

    private void BtnViewPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewPrescriptionActionPerformed
        // opens view prescription array
        new PatientViewPrescription(currentID).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnViewPrescriptionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             new PatientHome(currentID).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCreateDoctorFeedback;
    private javax.swing.JButton BtnRequestAppointment;
    private javax.swing.JButton BtnRequestDeletion;
    private javax.swing.JButton BtnViewPrescription;
    private javax.swing.JButton BtnViewhistory;
    private javax.swing.JButton BtnviewAppointment;
    private javax.swing.JLabel LblTitle;
    // End of variables declaration//GEN-END:variables
}
