/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Adminforms;

import DatabasePackage.SystemDatabase;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author afernandez
 */
public class AdminSendDoctorFeedback extends javax.swing.JFrame {

    /**
     * Creates new form AdminSendDoctorFeedback
     */
    static String currentUserID;
    public AdminSendDoctorFeedback(String userID) {
        initComponents();
        this.currentUserID = userID;
        SetCombValues();
    }
    public void SetCombValues(){
        ArrayList<String> a = new ArrayList<String>();
            for (int i = 0; i < SystemDatabase.userArray.size(); i++) {
                if (SystemDatabase.userArray.get(i).getUserID().charAt(0) == 'D') {
                a.add(SystemDatabase.userArray.get(i).getUserID());
            }
        }
        
        for (String value : a) {
                CombDocID.addItem(value); 
        }
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CombDocID = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        LblDocName = new javax.swing.JLabel();
        BtnViewFeedback = new javax.swing.JButton();
        BtnBack = new javax.swing.JButton();
        BtnSendFeedback = new javax.swing.JButton();
        LblRating = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtFeedback = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Send Doctor feedback");

        CombDocID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombDocIDActionPerformed(evt);
            }
        });

        jLabel3.setText("doctor's ID");

        LblDocName.setText("doctor (DOCTOR NAME)");

        BtnViewFeedback.setText("View feedback");
        BtnViewFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewFeedbackActionPerformed(evt);
            }
        });

        BtnBack.setText("Back");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });

        BtnSendFeedback.setText("Send Doctor feedback");
        BtnSendFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSendFeedbackActionPerformed(evt);
            }
        });

        LblRating.setText("Rating: ");

        jLabel4.setText("Notes");

        TxtFeedback.setColumns(20);
        TxtFeedback.setRows(5);
        jScrollPane2.setViewportView(TxtFeedback);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnSendFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CombDocID, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LblDocName, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnViewFeedback))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(LblRating))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CombDocID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(LblDocName)
                    .addComponent(BtnViewFeedback))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblRating)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnBack, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(BtnSendFeedback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CombDocIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombDocIDActionPerformed
        // TODO add your handling code here:
        var temp = SystemDatabase.FindUser(CombDocID.getSelectedItem().toString());
        LblDocName.setText("Dr. " + temp.getUserFirstname() + " " + temp.getUserSurname());
    }//GEN-LAST:event_CombDocIDActionPerformed

    private void BtnViewFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewFeedbackActionPerformed
        // TODO add your handling code here:
        String combValue = CombDocID.getSelectedItem().toString();
        TxtFeedback.setText("");

        for (int i = 0; i < SystemDatabase.doctorFeedbackArray.size(); i++) {
            if ((SystemDatabase.doctorFeedbackArray.get(i).getDoctorID().equals(combValue)) && ("unapproved".equals(SystemDatabase.doctorFeedbackArray.get(i).isAdminApproved())) ) {
                TxtFeedback.setText(SystemDatabase.doctorFeedbackArray.get(i).getNotes());
                LblRating.setText("Rating: " + SystemDatabase.doctorFeedbackArray.get(i).getRating());
                break;
                //SystemDatabase.doctorFeedbackArray.get(i));
            }
        }
        
    }//GEN-LAST:event_BtnViewFeedbackActionPerformed

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        // TODO add your handling code here:
        new AdminHome(currentUserID).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnBackActionPerformed

    private void BtnSendFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSendFeedbackActionPerformed
        // TODO add your handling code here:
        String combValue = CombDocID.getSelectedItem().toString();
        for (int i = 0; i < SystemDatabase.doctorFeedbackArray.size(); i++) {
            if ((SystemDatabase.doctorFeedbackArray.get(i).getDoctorID().equals(combValue)) && ("unapproved".equals(SystemDatabase.doctorFeedbackArray.get(i).isAdminApproved())) ) {
                SystemDatabase.doctorFeedbackArray.get(i).setNotes(TxtFeedback.getText());
                SystemDatabase.doctorFeedbackArray.get(i).setAdminApproved("approved");
                showMessageDialog(null, "Feedback Updated");
                SystemDatabase.saveDoctorFeedback();
                new AdminHome(currentUserID).setVisible(true);
                this.dispose();
                //TxtFeedback.setText(SystemDatabase.doctorFeedbackArray.get(i).getNotes());
                break;
                //SystemDatabase.doctorFeedbackArray.get(i));
            }
        }
        
    }//GEN-LAST:event_BtnSendFeedbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSendDoctorFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSendDoctorFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSendDoctorFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSendDoctorFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminSendDoctorFeedback(currentUserID).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack;
    private javax.swing.JButton BtnSendFeedback;
    private javax.swing.JButton BtnViewFeedback;
    private javax.swing.JComboBox<String> CombDocID;
    private javax.swing.JLabel LblDocName;
    private javax.swing.JLabel LblRating;
    private javax.swing.JTextArea TxtFeedback;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
