/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Adminforms;

import DatabasePackage.SystemDatabase;

/**
 *
 * @author afernandez
 */
public class AdminHome extends javax.swing.JFrame {

    /**
     * Creates new form AdminHome
     */
    private static AdminHome obj = null;
    
    static String currentUserID;
    public AdminHome(String userID) {
        initComponents();
        this.currentUserID = userID;
        LblTitle.setText("Welcome, " + SystemDatabase.FindUser(currentUserID).getUserFirstname());
        //LblTitle.setText("Welcome, " + SystemDatabase.FindUser(currentUserID));
    }
    
    //this makes sure there can only be one admin home page at any given time
        public static AdminHome getObj()
    {
        if (obj == null) {
            obj = new AdminHome(currentUserID);
        } return obj;
    }
    //public AdminHome(String userID)
    //{
    //    this.currentUserID = userID;
    //}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblTitle = new javax.swing.JLabel();
        BtnViewDoctorRatings = new javax.swing.JButton();
        BtnRemoveDocSecAccount = new javax.swing.JButton();
        BtnCreateDocSecAccount = new javax.swing.JButton();
        BtnSendDoctorFeedback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblTitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTitle.setText("Welcome, Admin ");

        BtnViewDoctorRatings.setText("View Doctor ratings");
        BtnViewDoctorRatings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnViewDoctorRatingsActionPerformed(evt);
            }
        });

        BtnRemoveDocSecAccount.setText("Remove Doctor/secretary");
        BtnRemoveDocSecAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRemoveDocSecAccountActionPerformed(evt);
            }
        });

        BtnCreateDocSecAccount.setText("Create doctor/Secretary Account");
        BtnCreateDocSecAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCreateDocSecAccountActionPerformed(evt);
            }
        });

        BtnSendDoctorFeedback.setText("Send Doctor feedback");
        BtnSendDoctorFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSendDoctorFeedbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BtnViewDoctorRatings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnCreateDocSecAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnRemoveDocSecAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnSendDoctorFeedback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnViewDoctorRatings, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(BtnSendDoctorFeedback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCreateDocSecAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnRemoveDocSecAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCreateDocSecAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCreateDocSecAccountActionPerformed

        //opens create doctor/secretary form
        new CreateDocSecAccount(currentUserID).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnCreateDocSecAccountActionPerformed

    private void BtnRemoveDocSecAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRemoveDocSecAccountActionPerformed
         //opens remove doctor/secretary form
        new RemoveDocSecAccount(currentUserID).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnRemoveDocSecAccountActionPerformed

    private void BtnViewDoctorRatingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnViewDoctorRatingsActionPerformed
         //opens view doctor ratings form
        new AdminViewDoctorRatings(currentUserID).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnViewDoctorRatingsActionPerformed

    private void BtnSendDoctorFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSendDoctorFeedbackActionPerformed
         //opens send doctor feedback form
        new AdminSendDoctorFeedback(currentUserID).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnSendDoctorFeedbackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome(currentUserID).setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCreateDocSecAccount;
    private javax.swing.JButton BtnRemoveDocSecAccount;
    private javax.swing.JButton BtnSendDoctorFeedback;
    private javax.swing.JButton BtnViewDoctorRatings;
    private javax.swing.JLabel LblTitle;
    // End of variables declaration//GEN-END:variables
}
